//========================================================================================
//  
//  $File: //depot/devtech/16.0.x/plugin/source/sdksamples/suppui/SuppUIFactoryList.h $
//  
//  Owner: Adobe Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2020/11/06 13:08:29 $
//  
//  $Revision: #2 $
//  
//  $Change: 1088580 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================

REGISTER_PMINTERFACE(SuppUIActionComponent, kSuppUIActionComponentImpl)
REGISTER_PMINTERFACE(SuppUISuppressedUI, kSuppUISuppressedUIImpl)
REGISTER_PMINTERFACE(SuppUISysFileData, kSuppUISysFileDataImpl)
REGISTER_PMINTERFACE(SuppUIQuickApplyFilterProvider, kSuppUIQuickApplyFilterProviderImpl)
REGISTER_PMINTERFACE(SuppUIQuickApplyFilterService, kSuppUIQuickApplyFilterServiceImpl)


//  Code generated by DollyXs code generator
