//========================================================================================
//  
//  $File: //depot/devtech/16.0.x/plugin/source/sdksamples/printselection/PrnSelFactoryList.h $
//  
//  Owner: Adobe Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2020/11/06 13:08:29 $
//  
//  $Revision: #2 $
//  
//  $Change: 1088580 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================

REGISTER_PMINTERFACE(PrnSelActionComponent, kPrnSelActionComponentImpl)
REGISTER_PMINTERFACE(PrnSelDrawHandler, kPrnSelDrawHandlerImpl)
REGISTER_PMINTERFACE(PrnSelPrintSetupProvider, kPrnSelPrintSetupProviderImpl)
REGISTER_PMINTERFACE(PrnSelData, kPrnSelDataImpl)
REGISTER_PMINTERFACE(PrnSelSuiteASB, kPrnSelSuiteASBImpl)
REGISTER_PMINTERFACE(PrnSelSuiteCSB, kPrnSelSuiteLayoutCSBImpl)
REGISTER_PMINTERFACE(PrnSelSuiteCSB, kPrnSelSuiteTableCSBImpl)
REGISTER_PMINTERFACE(PrnSelSuiteCSB, kPrnSelSuiteTextCSBImpl)
REGISTER_PMINTERFACE(PrnSelScriptProvider, kPrnSelScriptProviderImpl)
REGISTER_PMINTERFACE(PrnSelUtils, kPrnSelUtilsImpl)
// Generated by Dolly build 17: template "Dialog".
// End, PrnSelFactoryList.h.

